"""Adds one-to-many relationship between author and book models

Revision ID: 017a46ccd1db
Revises: c2b21861fc01
Create Date: 2024-03-20 17:25:35.114191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017a46ccd1db'
down_revision = 'c2b21861fc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
