"""Adds Genre model

Revision ID: 165ed80e2246
Revises: 017a46ccd1db
Create Date: 2024-03-21 08:57:54.485646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165ed80e2246'
down_revision = '017a46ccd1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###
