"""Adds Genre model

Revision ID: 56875edeb5fd
Revises: febdb51817ea
Create Date: 2024-03-22 11:05:39.382277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56875edeb5fd'
down_revision = 'febdb51817ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###
