"""Add book_genre model. Create many-to-many relationship between Book and Genre models.

Revision ID: 963232f06723
Revises: 165ed80e2246
Create Date: 2024-03-21 09:18:56.666656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963232f06723'
down_revision = '165ed80e2246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_genre',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_genre')
    # ### end Alembic commands ###
